[font]
size = 11.0
normal = {family = "Iosevka Term Nerd Font Mono"}
bold = {family = "Iosevka Term Nerd Font Mono", style = "Bold"}
italic = {family = "Iosevka Term Nerd Font Mono", style = "Italic"}
bold_italic = {family = "Iosevka Term Nerd Font Mono", style = "Bold Italic"}
builtin_box_drawing = true
offset = {x = 0, y = 0}

[window]
padding = {x = 12, y = 12}
dimensions = { columns = 120, lines = 40 }


[selection]
save_to_clipboard = true

[colors]
primary.background = "#eff1f5"
primary.foreground= "#4c4f69"

